version: '3.9'

services:
  backend:
    build: ./backend_byte
    container_name: flask_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend_byte:/app
    env_file:
      - ./backend_byte/.env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: sys_byte
      MYSQL_ROOT_PASSWORD: hsmg777
      MYSQL_USER: hsmg
      MYSQL_PASSWORD: hsmg777
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
